import { IMovie } from '@/models/models';

const movies: IMovie[] = [
  {
    id: 447365,
    title: 'Guardians of the Galaxy Vol. 3',
    tagline: 'Greatest movie you ever seen!',
    voteAverage: 10,
    voteCount: 9,
    releaseDate: '2020-05-01',
    posterPath: 'https://image.tmdb.org/t/p/w500/ldoY4fTZkGISMidNw60GHoNdgP8.jpg',
    overview: "The third film based on Marvel's Guardians of the Galaxy.",
    budget: 0,
    revenue: 0,
    genres: [
      'Action',
      'Adventure',
      'Science Fiction',
    ],
    duration: 130,
  },
  {
    id: 424785,
    title: 'Transformers 7',
    tagline: 'Greatest movie you ever seen!',
    voteAverage: 9,
    voteCount: 0,
    releaseDate: '2019-06-26',
    posterPath: 'https://image.tmdb.org/t/p/w500/432BowXw7a4fWXSONxBaFKqvW4f.jpg',
    overview: 'Plot unknown.',
    budget: 0,
    revenue: 0,
    genres: [
      'Science Fiction',
      'Action',
      'Adventure',
    ],
    duration: 130,
  },
  {
    id: 299534,
    title: 'Untitled Avengers',
    tagline: 'Greatest movie you ever seen!',
    voteAverage: 8,
    voteCount: 9,
    releaseDate: '2019-04-24',
    posterPath: 'https://image.tmdb.org/t/p/w500/aMETsaNNcDc6g5ZatQtVbySnSaA.jpg',
    overview: 'The culmination of the Marvel Cinematic Universe.',
    budget: 0,
    revenue: 0,
    genres: [
      'Action',
      'Adventure',
      'Science Fiction',
    ],
    duration: 130,
  },
  {
    id: 287947,
    title: 'Shazam!',
    tagline: 'Greatest movie you ever seen!',
    voteAverage: 7,
    voteCount: 5,
    releaseDate: '2019-04-05',
    posterPath: 'https://image.tmdb.org/t/p/w500/yUOJHa9XmB1H0iYodG9Kb3YCc9T.jpg',
    overview: "We all have a superhero inside us, it just takes a bit of magic to bring it out. In Billy Batson's case, by shouting out one word--SHAZAM!--this streetwise 14-year-old foster kid can turn into the adult superhero Shazam, courtesy of an ancient wizard.Still a kid at heart--inside a ripped, godlike body--Shazam revels in this adult version of himself by doing what any teen would do with superpowers: have fun with them! Can he fly? Does he have X-ray vision? Can he shoot lightning out of his hands? Can he skip his social studies test? Shazam sets out to test the limits of his abilities with the joyful recklessness of a child. But he'll need to master these powers quickly in order to fight the deadly forces of evil controlled by Doctor Thaddeus Sivana.",
    budget: 0,
    revenue: 0,
    genres: [
      'Action',
      'Adventure',
      'Fantasy',
      'Science Fiction',
    ],
    duration: 130,
  },
  {
    id: 320288,
    title: 'X-Men: Dark Phoenix',
    tagline: 'Greatest movie you ever seen!',
    voteAverage: 6,
    voteCount: 0,
    releaseDate: '2019-02-14',
    posterPath: 'https://image.tmdb.org/t/p/w500/6qmsupE0opYPIaBGe7T5D2FBzLs.jpg',
    overview: 'Gathered together by Professor Charles Xavier to protect a world that fears and hates them, the X-Men had fought many battles, been on adventures that spanned galaxies, grappled enemies of limitless might, but none of this could prepare them for the most shocking struggle they would ever face. One of their own members, Jean Grey, has gained power beyond all comprehension, and that power has corrupted her absolutely! Now, they must decide if the life of the woman they cherish is worth the existence of the entire universe!',
    budget: 0,
    revenue: 0,
    genres: [
      'Action',
      'Science Fiction',
    ],
    duration: 130,
  },
  {
    id: 181790,
    title: 'Journey 3: From the Earth to the Moon',
    tagline: 'Greatest movie you ever seen!',
    voteAverage: 5,
    voteCount: 7,
    releaseDate: '2018-12-31',
    posterPath: 'https://image.tmdb.org/t/p/w500/98tbNloMBztAVnWpAznKKVUdi2O.jpg',
    overview: 'Sean and Hank go on their biggest adventure yet, to the moon.',
    budget: 0,
    revenue: 0,
    genres: [
      'Action',
      'Adventure',
      'Fantasy',
      'Science Fiction',
    ],
    duration: 130,
  },
  {
    id: 297802,
    title: 'Aquaman',
    tagline: 'Greatest movie you ever seen!',
    voteAverage: 4,
    voteCount: 0,
    releaseDate: '2018-12-19',
    posterPath: 'https://image.tmdb.org/t/p/w500/sshNRCbtU2ON8SiWLycQzr05doX.jpg',
    overview: 'Following the events of Justice League, Arthur Curry, the reluctant ruler of the underwater kingdom of Atlantis, is caught between surface dwellers and his own people who are ready to lash out and invade the surface.',
    budget: 160000000,
    revenue: 0,
    genres: [
      'Action',
      'Fantasy',
      'Science Fiction',
    ],
    duration: 130,
  },
  {
    id: 353081,
    title: 'Mission: Impossible - Fallout',
    tagline: 'Greatest movie you ever seen!',
    voteAverage: 5.5,
    voteCount: 3,
    releaseDate: '2018-07-26',
    posterPath: 'https://image.tmdb.org/t/p/w500/A2W75CVz9l8gEeWhQiiftlOCkgi.jpg',
    overview: 'The sixth installment in the "Mission: Impossible". When an IMF mission ends badly, the world is faced with dire consequences. As Ethan Hunt takes it upon himself to fulfil his original briefing, the CIA begin to question his loyalty and his motives. The IMF team find themselves in a race against time, hunted by assassins while trying to prevent a global catastrophe.',
    budget: 0,
    revenue: 0,
    genres: [
      'Adventure',
      'Action',
      'Thriller',
    ],
    duration: 130,
  },
  {
    id: 351286,
    title: 'Jurassic World: Fallen Kingdom',
    tagline: 'Life finds a way',
    voteAverage: 6.8,
    voteCount: 28,
    releaseDate: '2018-06-01',
    posterPath: 'https://image.tmdb.org/t/p/w500/ln6d5Okr6VK5vfQVobJTiYxeD0l.jpg',
    overview: 'A volcanic eruption threatens the remaining dinosaurs on the island of Isla Nublar, where the creatures have freely roamed for several years after the demise of an animal theme park known as Jurassic World. Claire Dearing, the former park manager, has now founded the Dinosaur Protection Group, an organization dedicated to protecting the dinosaurs. To help with her cause, Claire has recruited Owen Grady, a former dinosaur trainer who worked at the park, to prevent the extinction of the dinosaurs once again.',
    budget: 0,
    revenue: 0,
    genres: [
      'Action',
      'Adventure',
      'Drama',
      'Science Fiction',
      'Thriller',
    ],
    duration: 130,
  },
  {
    id: 348350,
    title: 'Solo: A Star Wars Story',
    tagline: 'Greatest movie you ever seen!',
    voteAverage: 5.1,
    voteCount: 2,
    releaseDate: '2018-05-23',
    posterPath: 'https://image.tmdb.org/t/p/w500/uJ6OnE3CzGWq6buLINAbdBqa0gV.jpg',
    overview: 'Through a series of daring escapades deep within a dark and dangerous criminal underworld, Han Solo meets his mighty future copilot Chewbacca and encounters the notorious gambler Lando Calrissian.',
    budget: 0,
    revenue: 0,
    genres: [
      'Action',
      'Adventure',
      'Family',
      'Science Fiction',
    ],
    duration: 130,
  },
  {
    id: 348351,
    title: 'The Rock',
    tagline: 'Greatest movie you ever seen!',
    voteAverage: 9.2,
    voteCount: 2,
    releaseDate: '1996-02-01',
    posterPath: 'https://www.themoviedb.org/t/p/w500/j5mxLNWjUlXUUk8weFBtnF4afIR.jpg',
    overview: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
    budget: 0,
    revenue: 0,
    genres: [
      'Action',
    ],
    duration: 130,
  },
  {
    id: 348352,
    title: 'Interstellar',
    tagline: 'Greatest movie you ever seen!',
    voteAverage: 10,
    voteCount: 2,
    releaseDate: '2014-01-01',
    posterPath: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1600647/78c36c0f-aefd-4102-bc3b-bac0dd4314d8/1920x',
    overview: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
    budget: 0,
    revenue: 0,
    genres: [
      'Adventure',
      'Science Fiction',
    ],
    duration: 130,
  },
];

export default movies;
